title: Identification of Antimicrobial Peptides from the Human Gut Microbiome using Deep Learning.
description: A look at how deep learning can help aid in the fight against pathogens
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
